version: "3"

networks:
  web:
    external: true

services:
  nginx-test:
    image: nginx:latest
    restart: unless-stopped
    labels:
      - traefik.http.routers.nginx-test.rule=Host(`nginx.pygenai.com`)
      - traefik.http.routers.nginx-test.tls=true
      - traefik.http.routers.nginx-test.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web